import 'package:flutter/material.dart';
import 'package:carousel_pro/carousel_pro.dart';

class Wipro extends StatefulWidget {
  @override
  _WiproState createState() => _WiproState();
}

class _WiproState extends State<Wipro> {
  @override
  Widget build(BuildContext context) {
    Widget image_slider_carousel = Padding(
        padding: EdgeInsets.all(7.50),
        child: Container(
          height: 200.0,
          decoration: BoxDecoration(borderRadius: BorderRadius.circular(10.0)),
          child: Carousel(
            boxFit: BoxFit.fill,
            images: [
              AssetImage("images/w1.jpg"),
              AssetImage("images/w2.jpg"),
              AssetImage("images/w3.jpg"),
              AssetImage("images/w4.jpg"),
              AssetImage("images/w5.jpg")
            ],
            indicatorBgPadding: 1.0,
          ),
        ));
    return Scaffold(
      appBar: AppBar(
          title:
              Text(" \t \t WIPRO \t \t ", style: TextStyle(fontFamily: 'Abel')),
          backgroundColor: Color(0xFF5C6BC0)),
      body: ListView(
        children: <Widget>[
          image_slider_carousel,
          Container(
            color: Color(0xFFE3F2FD),
            child: Padding(
                padding: EdgeInsets.all(15.0),
                child: Column(
                  children: [
                    Text(
                      " \n Wipro Limited is a market leading Information Technology, consulting and"
                      " business process services company. Wipro utilizes the power of analytics,"
                      " robotics, cloud and other emerging technologies to help clients spread across six different"
                      " continents to adapt to the current digital trend and help them thrive to success."
                      " Wipro has over 1,60,000 dedicated employees serving together and building a bold and new future. "
                      "The amount of revenue generated by Wipro in the financial year 2017 is 848 crores USD.",
                      style: TextStyle(fontFamily: 'Abel', fontSize: 15.0),
                      textAlign: TextAlign.justify,
                    ),
                    Text(
                      "\n \t \t \t Wipro History \t \t \t \n",
                      style: TextStyle(
                          fontFamily: 'Roboto',
                          fontSize: 15.0,
                          fontWeight: FontWeight.w700),
                    ),
                    Text(
                      " \n \t \t Organisation Head \t \t \n",
                      style: TextStyle(
                          fontFamily: 'Roboto',
                          fontWeight: FontWeight.w700,
                          fontSize: 15.0),
                    ),
                    Text(
                      "\n1. Azim Premji is the chairman of Wipro Limited.\n"
                      "2. Abidali Neemuchwala is the CEO of Wipro.\n"
                      "3. Rishad Premji is the Chief strategy officer in Wipro.\n",
                      style: TextStyle(fontFamily: 'Abel', fontSize: 15.0),
                    ),
                    Text(
                      "\n \t \t \t Geographical Presence \t \t \t \n",
                      style: TextStyle(
                          fontFamily: 'Roboto',
                          fontSize: 15.0,
                          fontWeight: FontWeight.w700),
                    ),
                    Text(
                      "\n Wipro is a global IT company currently present across 54 countries across the globe, "
                      "offering IT solutions and services which includes Systems Integration, Consulting, R&D Services,"
                      " Information Systems Outsourcing, IT-Enabled Services etc.\n \n Wipro has presence across entire India\n"
                      "\t\t* East:"
                      "\n1. Kolkata"
                      "\n2. Guwahati"
                      "\n3. Bhubaneswar"
                      "\n\t\t* West:"
                      "\n1. Pune"
                      "\n2. Mumbai"
                      "\n3. Ahmedabad"
                      "\n4. Baroda"
                      "\n\t\t* North:"
                      "\n1. New Delhi"
                      "\n2. Noida"
                      "\n3. Gurugram"
                      "\n4. Jaipur"
                      "\n\t\t* South:"
                      "\n1. Bengaluru"
                      "\n2. Chennai"
                      "\n3. Hyderabad"
                      "\n4. Visakhapatnam"
                      "\n5. Coimbatore"
                      "\n6. Mysore"
                      "\n7. Secunderabad"
                      "\n8. Cochin"
                      "\n9. Vijayawada",
                      style: TextStyle(fontFamily: 'Abel', fontSize: 15.0),
                    ),
                    Text(
                      " \n \t \t \t Wipro Vision \t \t \t \n",
                      style: TextStyle(
                          fontFamily: 'Roboto',
                          fontSize: 15.0,
                          fontWeight: FontWeight.w700),
                    ),
                    Text(
                      "\n To earn our clients' trust  and maximize the value of their business by providing solutions that "
                      "integrate deep industry insights, leading technologies and best in class delivery process.",
                      style: TextStyle(fontFamily: 'Abel', fontSize: 15.0),
                      textAlign: TextAlign.justify,
                    ),
                    Text(
                      " \n \t \t Headquartees of the Company \t \t \n",
                      style: TextStyle(
                          fontFamily: 'Roboto',
                          fontSize: 15.0,
                          fontWeight: FontWeight.w700),
                    ),
                    Text(
                      "\n Bangalore, Karnataka, India ",
                      style: TextStyle(fontFamily: 'Abel', fontSize: 15.0),
                    ),
                    Text(
                      " \n \t \t \t Wipro Tagline \t \t \t \n",
                      style: TextStyle(
                          fontFamily: 'Roboto',
                          fontSize: 15.0,
                          fontWeight: FontWeight.w700),
                    ),
                    Text(
                      ' \n Wipro previously had a tagline " Applying thought"  from (1998-2017) but now it has been retired.'
                      '\n In 2017 Wipro Launched New Logo for new brand identity and rearticulated "Spirit of Wipro"'
                      " to underscore wipro's commitment to transformation & evolving client expectation."
                      "\n Wipro follow below principles \n"
                      "\n 1. Be passionate about client's success"
                      "\n 2. Be global and responsible"
                      "\n 3. Treat each person with respect"
                      "\n 4. Unyielding integrity in everything we do",
                      style: TextStyle(fontFamily: 'Abel', fontSize: 15.0),
                      textAlign: TextAlign.justify,
                    ),
                    Text(
                      "\n \t \t Awards and Recgonition \t \t \n",
                      style: TextStyle(
                          fontFamily: 'Roboto',
                          fontSize: 15.0,
                          fontWeight: FontWeight.w700),
                    ),
                    Text(
                      " \n •	Wipro won the Quest Forum Global Sustainability Awards in the software category for the year 2017."
                      " \n •	Wipro won the Most Admired Knowledge Enterprise (MAKE) Award for the year 2017."
                      ' \n •	Wipro won the "Best Internet of Things  Solution Partner Award" by Cisco.'
                      " \n •	Wipro’s Next Generation Customer Experience (NGCE) platform won the “Best Innovation Practices for Science and Technology Service Industry in China” award."
                      " \n •	In the FTSE4Good Index Series in 2017, Wipro has been named a constituent."
                      " \n •	For the year 2017, Wipro was selected as a member of Vigeo Eiris Emerging Market Sustainability Index (the 70 most advanced companies in the Emerging Market Region).\n",
                      style: TextStyle(
                        fontFamily: 'Abel',
                        fontSize: 15.0,
                      ),
                      textAlign: TextAlign.justify,
                    )
                  ],
                )),
          )
        ],
      ),
    );
  }
}
